local mod = dmhub.GetModLoading()

--This file implements the rules for in-game Languages (like Orcish, Elvish, etc. See Translation for the file which
--allows translating DMHub into other real-world languages).

--- @class Language: GameType
--- @field new fun(o?: table): Language
--- @field id string Key of this row in its data table; SetAndUploadTableItem sets it.
--- @field name string Display name (e.g. "Elvish", "Common").
--- @field type string Language type (e.g. "Standard", "Exotic", "Secret").
--- @field speakers string Description of who speaks this language.
--- @field description string Lore/descriptive text.
--- @field typicalSpeakers table Typical speaker creature types.
--- @field script string Writing system name (e.g. "Common", "Dwarvish").
--- @field group string UI group label (e.g. "Custom", "Standard").
--- @field commonality number Commonality rating (higher = more common).
--- @field dead boolean If true, this is a dead language not spoken by living creatures.
--- @field tableName "languages" Data table name ("languages").
Language = RegisterGameType("Language")

--standard language fields.
Language.name = "New Language"
Language.type = "Standard"
Language.speakers = ""
Language.description = ""
Language.typicalSpeakers = {}
Language.script = "Common"
Language.group = "Custom"

Language.commonality = 5
Language.dead = false

Language.tableName = "languages"

--The writing systems a language can be written in. `font` is the font its
--writing appears in for a reader who doesn't know the language. A language
--whose `script` isn't listed here falls back to the first entry, Common.
--The non-Tengwar fonts are generated by tools/script-fonts in the engine repo.
Language.scripts = {
    { id = "Common", text = "Common", font = "Tengwar" },
    { id = "Elvish", text = "Elvish", font = "Tengwar" },
    { id = "Dwarvish", text = "Dwarvish runes", font = "DwarvishRunes" },
    { id = "Goblin", text = "Goblin fingernail script", font = "GoblinScratch" },
    { id = "Infernal", text = "Infernal contract hand", font = "InfernalScript" },
}

--- The font that shows this language's writing to a reader who can't read it.
--- @return string
function Language:UnreadableFont()
    for _, script in ipairs(Language.scripts) do
        if script.id == self.script then
            return script.font
        end
    end
    return Language.scripts[1].font
end

--- The unreadable-writing font for a language id; an unknown or missing id
--- gets the Common script's font.
--- @param langid string|nil
--- @return string
function Language.UnreadableFontForId(langid)
    local language = langid ~= nil and (dmhub.GetTable(Language.tableName) or {})[langid] or nil
    if language == nil then
        return Language.scripts[1].font
    end
    return language:UnreadableFont()
end

--- The unreadable-writing font for a language named in authored text (e.g.
--- an EotW script's "Yllyric"), matched case-insensitively; an unknown name
--- gets the Common script's font.
--- @param name string|nil
--- @return string
function Language.UnreadableFontForName(name)
    local key = string.lower(name or "")
    for _, language in unhidden_pairs(dmhub.GetTable(Language.tableName) or {}) do
        --- @cast language Language
        if string.lower(language.name or "") == key then
            return language:UnreadableFont()
        end
    end
    return Language.scripts[1].font
end

--- @return Language
function Language.CreateNew()
	return Language.new{
	}
end

--- @return DropdownOption[]
function Language.GetDropdownList()
	local result = {}
	local languagesTable = dmhub.GetTable('languages')
	for k,v in unhidden_pairs(languagesTable) do
		result[#result+1] = { id = k, text = v.name }
	end
	table.sort(result, function(a,b)
		return a.text < b.text
	end)
	return result
end

local SetLanguage = function(tableName, languagePanel, langid)
	local languageTable = dmhub.GetTable(tableName) or {}
	local language = languageTable[langid]
	local UploadLanguage = function()
		dmhub.SetAndUploadTableItem(tableName, language)
	end

	local children = {}

	if devmode() then
        --the id of the language.
        children[#children+1] = gui.Panel{
            classes = {"formStackedRow"},
            gui.Label{
                classes = {"formStacked"},
                text = "ID:",
            },
            gui.Input{
                classes = {"formStacked"},
                text = language.id,
                editable = false,
            },
        }
    end

	--the name of the language.
	children[#children+1] = gui.Panel{
		classes = {"formStackedRow"},
		gui.Label{
			classes = {"formStacked"},
			text = "Name:",
		},
		gui.Input{
			classes = {"formStacked"},
			text = language.name,
			change = function(element)
				language.name = element.text
				UploadLanguage()
			end,
		},
	}

	--the group of the language
	children[#children+1] = gui.Panel{
		classes = {"formStackedRow"},
		gui.Label{
			classes = {"formStacked"},
			text = "Group:",
		},
		gui.Input{
			classes = {"formStacked"},
			text = language.group,
			change = function(element)
				language.group = element.text
				UploadLanguage()
			end,
		},
	}

	--the script it is written in, which picks the font unreadable text shows in.
	children[#children+1] = gui.Panel{
		classes = {"formStackedRow"},
		gui.Label{
			classes = {"formStacked"},
			text = "Script:",
		},
		gui.Dropdown{
			classes = {"formStacked"},
			options = Language.scripts,
			idChosen = language.script,
			change = function(element)
				---@cast element Dropdown
				language.script = element.idChosen --[[@as string]]
				UploadLanguage()
			end,
		},
	}

		--language speakers
	children[#children+1] = gui.Panel{
		classes = {"formStackedRow"},
		gui.Label{
			classes = {"formStacked"},
			text = "Native Speakers:",
		},
		gui.Input{
			classes = {"formStacked"},
			text = language.speakers,
			change = function(element)
				language.speakers = element.text
				UploadLanguage()
			end,
		},
	}

	--language description..
	children[#children+1] = gui.Panel{
		classes = {"formStackedRow"},
		gui.Label{
			classes = {"formStacked"},
			text = "Description:",
		},
		gui.Input{
			classes = {"formStacked"},
			height = 80,
			text = language.description,
			multiline = true,
			textAlignment = "topLeft",
			change = function(element)
				language.description = element.text
				UploadLanguage()
			end,
		}
	}
	
	children[#children+1] = gui.Check{

        halign = "left",
        valign = "top",
        text = "Dead Language",
        value = language.dead,

		change = function(element)
			if element.value == true then
				language.dead = true
			else
				language.dead = false
			end
			UploadLanguage()
		end,
    }

    children[#children+1] = gui.Panel{
        classes = {"formStackedRow"},
        gui.Label{
            classes = {"formStacked"},
            text = "Commonality:",
        },
        gui.Input{
            classes = {"formStacked"},
            text = tostring(language.commonality),
            change = function(element)
                -- Bad input writes nil, which clears the row's value so reads fall back to the default.
                ---@diagnostic disable-next-line: assign-type-mismatch
                language.commonality = tonumber(element.text)
                element.text = tostring(language.commonality)
                UploadLanguage()
            end,
        }
    }

	

	languagePanel.children = children
end

function Language.CreateEditor()
	local languageEditor
	languageEditor = gui.Panel{
		data = {
			SetLanguage = function(tableName, langid)
				SetLanguage(tableName, languageEditor, langid)
			end,
		},
		vscroll = true,
		width = 1200,
		height = "90%",
		halign = "left",
		flow = "vertical",
		pad = 20,
		borderBox = true,
	}

	return languageEditor

end

